### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by happnatious1** [Yortw/RSSDP#10]
Will this project compile in VS2010 sp1? When I open the solution file I get lots of errors about most of the files not being compatible with this version. If a create a simple console project and reference the dll's in the packages folder visual studio complains because rssdp is compiled with .net 4.0.3 but it also wants a reference to system.net.http version 1.5 which isn't in .net 4.0.3.  What am I missing here?

**Comment by Yortw** [comment]
Hi,

Sorry, but I don't have VS2010 to test with (or the disk space to install it). The code was written with 2013 and 2015. While I didn't deliberately make it incomaptible with 2010 I may well have used unsupported project types or syntax for the IDE and compiler of that age. I'm not sure what "files" would be "incompatible" or why, unless it was the PCL libraries either being unsupported or targeting unknown platforms.

As for your console project, that should defintely work (the test/sample app in the repository is a console app, and .Net 4 is a supported target of the library). It *sounds* like your problem is you've tried to setup the references manually and haven't done a complete job. By far the easiest way to make this work is going to be to use the Nuget package. https://visualstudiogallery.msdn.microsoft.com/27077b70-9dad-4c64-adcf-c7cf6bc9970c seems like it has a 2010 compatible version of the Nuget package manager if that's not already included in your VS2010 install. From the package manager, install the 'RSSDP' package (http://www.nuget.org/packages/Rssdp/).

Assuming you can't do that for some reason, then you need to obtain and reference the dependencies used by RSSDP. You specifically mentioned System.Net.Http which I believe is one of those dependencies (Microsoft.Net.Http). RSSDP is dependent on the following nuget packages;

            <dependency id="Microsoft.Net.Http" version="2.2.29" />
            <dependency id="Microsoft.Bcl.Async" version="1.0.168" />

These are used for async/await and httpclient support on platforms that don't support one or other natively (I think 4.03 is in that list). You will need to download and unpack the binaries from those files, and then add the references to the binaries for the platform(s) you're working with to the same project(s) referencing the RSSDP assemblies. I am not sure if there is anything else you need to do - it maybe the Microsoft.Bcl.Async package also modified the build targets in the csproj when installed by Nuget. Easiest way to tell would be to install the Nuget package using a version of VS that supports it and see what changes are made to the csproj.

Again, the easiest way to get this to work is to use the Nuget package which does all this for you.

Hope that helps.

**Comment by happnatious1** [comment]
Thank you for your response. There were indeed multiple syntax errors so I installed visual studio 2015 and everything works perfectly.

**Comment by Yortw** [comment]
:+1:
