### ISSUE TITLE
Network enumeration

### ISSUE THREAD

**Issue by smartmeter** [Yortw/RSSDP#16]
Hi, how can I enumerate over the network in both IP v4 and and V6 and reconcile the discovery.

**Comment by Yortw** [comment]
Short anser is, you can't, sorry. See #16 - IPv6 is not currently supported by the library.

While it's a moot point, it's also unclear what you mean by 'reconcile'. Did you mean a distinct list, or a list of devices grouped together when they're the same device on different addresses, or just a raw union of the two lists or something else? Any of that could be done with LINQ or the LINQ extension methods, but since you can't search on ipv6 with RSSDP, you're out of luck (or need a new library).

**Comment by smartmeter** [comment]
Right now when I try to discover on the network (I added some IPV6 discovery, unreliably), the *discovered devices* sometimes show up twice under a) different protocols V4, V6 or b) multiple NICs. 
I wanted to reconcile those and show the devices with 2 or 3 NIC's

I guess we can live without IPV6, its just that they end up as ghost devices in the network.

What was I trying to do: I was looking to take stock of what devices are on the network. I have a graph that I wanted to add and contribute to this lib, but I need to enumerate all the devices build a network browser and then add it to the graph.

**Comment by Yortw** [comment]
Assuming you have a list of ipv6 devices represented using the SsdpDiscoveredDevice class from this library then you should be able to use LINQ and the GroupBy functionality to group devices by USN.

This is off the top of my head, so may need modification to make it actually compile/work, but something like this;


```c#
var ip4Devices = GetIp4Devices();
var ip6Devices = GetIp6Devices();

var reconciledDevices = from d in ip4Devices.Union(ip6Devices) 
              group d by d.Usn into dg 
              select new { Usn = dg.Key, Devices = dg.ToList() };
```

That should give you an IEnumerable of an anonymous type. The anonymous type will have a Usn property which is the unique identifier of the device, and the anonymous type itself will also be an ienumerable (List?) of devices that match that USN. Again, this is pseduo code written from memory without any tools so I probably got some details wrong, but the basic idea should be there.
