### ISSUE TITLE
RSSDP on Uwp

### ISSUE THREAD

**Issue by mterwoord** [Yortw/RSSDP#17]
I'm trying to use RSSDP on Uwp (planning to do something fun with win IoT)
When running the package, I get errors about IP addresses not being found. I forked and ran with the sources, and then I get an issue due to AutomacDecompression stuff. 
Maybe this is due to portable libraries being used. I'd suggest using shared projects instead.

**Comment by mterwoord** [comment]
It seems the error I get with Nuget is related to the event driven discovery. In UwaUdpSocket.GetLocalIPInfo, I get the following error: ```Could not find adapter from local IP address```

If I remove the following part from the linq query in that method, everything works fine: 
```n.DisplayName == _LocalIPAddress```

**Comment by Yortw** [comment]
Hi,

Sorry you're having problems with RSSDP. 

There may well be a bug that requires a code change, but I cannot reproduce it. Not only does it work on my local dev machine, but I have a commercial UWP application deployed mostly to phones, but also working on tablets and desktops, which is using the Nuget package without this error. As a result, I think at least half the cause is probably environmental, and since I can't reproduce I will need your help to diagnose.

I can't simply remove the line you've suggested, as it was added to solve #2 and may also be used in part for #6, I think.

In terms of figuring out a working solution, can you please provide some more details;

1. What kind of device are you running on? You mentioned IoT, so is this a RP2 or an Arduino etc?
2. What kind of project template did you use for the project - I know there are some templates for IoT that are slightly different from the default "Windows Store" projects. 
3. How many adapters does the UWP framework return in that linq statement (without the where clause)?
4. For each adapter, what is it's 'DisplayName' value?
5. Can you see any other property on the adapter that will allow matching on IP, for the adapter you are trying to connect to?
6. Can you show your code for setting up the RSSDP objects? Are you passing in a local IP value to one of the object constructors?

Thanks for your assistance.

**Comment by mterwoord** [comment]
Not sure what I goofed up, but somehow I cannot reproduce this now...

**Comment by mterwoord** [comment]
So I say we discard the issue. I'll close it.

**Comment by mterwoord** [comment]
Reopening. Found out what I did wrong:
I called StartListeningForNotifications before starting search.

**Comment by Yortw** [comment]
Thanks for reporting this. I think I've reproduced and fixed the problem. An upddate has just been pushed to Nuget and should be available within 15 mins or so.
