### ISSUE TITLE
SSDP devices do not show in Windows Network overview

### ISSUE THREAD

**Issue by ramondeklein** [Yortw/RSSDP#23]
I have published SSDP devices. Although the devices can be found using the SsdpDeviceLocator class, they are not visible with Intel's Device Sniffer or Windows Network overview.

**Comment by Yortw** [comment]
Hi,

I've retested this morning and it is working for me on both Win10 and Win 7 machines (I don't have any other OS's/devices to test with at present).

If you're seeing the broadcast notifications (via the locator class) but it doesn't show in Windows Explorer/Intel Device Spy etc then the problem is *likely* with your device description document. The locator class raises events/captures results when it receives the notification packet, it leaves getting and parsing the DDD to you if you care. Windows Explorer and many UPnP utility attempt to show full device details which can only be done if they can access the DDD. Many of them also further validate the content of the DDD against both the UPnP spec AND the content of the notification/search response packet. If the DDD has a different base URL, device ID, device type etc. to the notification/search packet then they do not show the device.

I spent a couple of hours reading MSDN articles about Windows networking, but didn't find anything specific to the requirements for SSDP published devices to show in Windows Explorer, and as I say it's working for me. I would start by checking your DDD. Ensure it is accessible, without any kind of auth, using an HTTP GET from the location specified in the notification/search response. You should be able to browse to the url in a browser and see the xml response. Make sure the DDD is valid XML matches the UPnP schema. If all of that is ok, make sure the values relating to the device (id, type, location etc) match in both places.

Other than that, I'm not sure what to suggest.

**Comment by ramondeklein** [comment]
Thanks for your reply. It seems that I had an error in the device description. It seems to work now. Thanks for your support.

**Comment by Yortw** [comment]
Glad you got it working, thanks for letting me know and closing issue.
