### ISSUE TITLE
Signed assembly on NuGet

### ISSUE THREAD

**Issue by ramondeklein** [Yortw/RSSDP#25]
Could you provide signed assemblies via NuGet? We use an application that is signed and therefor requires signed assemblies.

**Comment by Yortw** [comment]
Hi,

The answer is, I don't know. I would really like to say yes and see you adopt the library, but signing the current assemblies would cause me deployment grief and possibly hurt other existing users. I could create a second package, but that's a lot more work for me and apparently it's bad idea because other library authors that might take a dependency on this then have a tough choice. Also, the signing process makes it more difficult to fork and mod the code, unless I include the key in the repo - which is technically ok because signing doesn't provide any security and so exposing the key isn't much of a problem (and many OSS projects do this). However, if your reason for wanting signed binaries is because someone at your office thinks it's more secure (even though it's not), then that would defeat the purpose of signing it for you anyway. I've spent about 3 hours so far researching what the right way of handling this is and I'm still a bit lost.

If I can figure out the right plan, then by all means I'll provide something. In the meantime, I understand there is a process (possibly awkward) where you could sign the binaries yourself?

What is your reason for signing? Are you trying to load multiple versions into the same app domain, or is it a political requirement around the misunderstanding of the (lack of) security provided by signing?

**Comment by Rambalac** [comment]
@Yortw, unsigned assemblies cannot be used in signed app.

Fortunately there are some NuGet packages which will sign for unsigned assemblies like **.NET Assembly Strong-Name Signer**

**Comment by Yortw** [comment]
Due to the potential issues and challenges with strong naming, and given their are solutions such as the [assembly strong naming toolkit](https://www.nuget.org/packages/Nivot.StrongNaming/1.0.4.2) I'm going to mark this won't fix. I would recommend trying that tool kit.

**Comment by Rambalac** [comment]
It's not a challenge, it's just check box in project settings.

**Comment by Yortw** [comment]
To enable signing yes, but where as some people want/need signing (usually for the wrong reasons), other people explicitly do NOT want strong named assemblies, and having them can create deployment issues in some situations. That fact that json.net is strong named causes me some serious dll hell at work for example. Some projects handle this by publishing two packages, one signed one unsigned, but that takes extra effort and really just pushes the problem downstream. Those are the sorts of challenges I was referring to (let alone whether the signing cert should be source controlled or not, who should have access if something happens to me or I abandon project etc).
