### ISSUE TITLE
Published SSDP Device Not visible on Local Network

### ISSUE THREAD

**Issue by parv0888** [Yortw/RSSDP#26]
I have successfully published the device in my console app.
The device is visible on the system running the console app. But on the other computers running on the same network the device is not being shown.

**Comment by Yortw** [comment]
Hi,

It is typically difficult to diagnose these issues remotely, as it is often caused by network/firewalls, or by incorrect publishing of the service or device description document.

You might like to start by checking the suggestions in these previous issues, and then follow up again here if you can't solve it using those. Also make sure you're using the latest version of the Nuget package.

https://github.com/Yortw/RSSDP/issues/21

https://github.com/Yortw/RSSDP/issues/19

It's also possible if you have multiple NIC's that the publisher is being bound to the wrong one, see the end of this issue for how to specify the IP address of the NIC to bind on;

https://github.com/Yortw/RSSDP/issues/2

The big issues are; 

1. Make sure no firewall blocking on either client or server (inbound & outbound for UDP multicast on appropriate ports).

2. Make sure the end point for your device description document is accessible from the remote machines.

3. Make sure the XML returned from the device description document url is valid XML and contains exactly the same UUID/device type etc. as you configured the publisher with (should do if you used RSSDP to generate the document).

4. Try using Intel's Device Spy on the client to see if it is receiving the packets at all.

Good luck, let me know if none of that helps.

**Comment by parv0888** [comment]
Hi, Thanks for a prompt reply. My router was consuming the SSDP Multicast and not forwarding it.

**Comment by Yortw** [comment]
Excellent, glad you found the solution. Thanks updating and closing the issue.
