### ISSUE TITLE
PCL support

### ISSUE THREAD

**Issue by tapanila** [Yortw/RSSDP#27]
If I would do a pull request to support PCL development using Bait and Switch would you accept that?

**Comment by Yortw** [comment]
Hi,

Thanks for asking (and considering a PR!).

I love PR's and I have no problem with a Bait PCL in theory! In practice, it would depend on the PR itself. If it was done 'properly' (from the TweetSharp architecture view), so that regenerating the TweetSharp code using the T4 template also updated the PCL, then yeah, I'd love it. If it's a manual implementation that has to be hand maintained, I'm not sure, but probably not.

**Comment by tapanila** [comment]
Hey,

The pull request would now be ready. It does not break any APIs or namespaces and keeps working if people update their nuget packages.

Any comments or thoughts?
