### ISSUE TITLE
IPV6 support

### ISSUE THREAD

**Issue by kakone** [Yortw/RSSDP#3]
Hello,

It lacks IPV6 support (multicast address : FF02::C).

Cordially,
Stéphane.

**Comment by Yortw** [comment]
Yes, this is a known/deliberate design issue. I don't have a suitable ipv6 network or devices to test with, I am unfamiliar with the technology and addressing schemes, and my use cases don't require support for it. If the situation changes or I find myself with 'spare time' I may add support. Otherwise, I would be delighted to accept a PR that added support for this.

Thanks for pointing it out though. Good to have it documented publicly.

**Comment by kakone** [comment]
It works like IPV4. To search the devices, instead of using the IPV4 multicast adress  "239.255.255.250", you must use "FF02::C" for IPV6 network adapters. The port is the same (1900).
This is what I do in my own SSDP library and it works well : https://github.com/kakone/SSDP.Portable/blob/master/UPnP/SsdpBase.cs

**Comment by Yortw** [comment]
Thanks for the info, I appreciate it. However the difficulty lies not in the implementation of the protocol, but in doing a good job of the RSSDP interfaces/API to make it work. Given the existing code there are design considerations that need to be taken into account.
