### ISSUE TITLE
Publish gets stuck a while

### ISSUE THREAD

**Issue by Reginiano** [Yortw/RSSDP#31]
Hi Yortw,
I'm publishing upnp by a windows service.
I'm running the following code every x seconds:

````
var deviceDefinition = new SsdpRootDevice()
{
    CacheLifetime = 30,
    Location = G.Location,
    DeviceTypeNameSpace = G.DeviceTypeNamespace,
    DeviceType = G.DeviceType,
    FriedlyName = G.FriendlyName,
    Manufacturer = G.Manufacturer,
    ModelName = G.ModelName,
    Uuid = G.Uuid
}

_Publisher = new SsdpDevicePublisher();
_Publisher.AddDevice(deviceDefinition);
```
It works great for a while, but after about 2,000 times- it gets stuck on the "_Publisher.AddDevice".
It does not respond even to a Thread.Abort(), so i can't even handle this as an exception.

Why does it happen:question:  :/

**Comment by Yortw** [comment]
I don't know, I've never tried doing that because it's not correct use of the library.

You're not disposing the old publisher before you create a new one, so perhaps you're bumping up against some kind of limit on the number of open sockets or the number of shared processes on a socket. Potentially you're just allocating a lot of stuff which the GC takes a while to clean up. 

It's unclear from the sample which thread you tried to call Abort on, so I can't tell if that even should work or not.

Basically, you shouldn't do this. Create one publisher per NIC you want to publish on (based on your local IPs). Do this on startup (or if your config file changes in a way that changes the publish data etc). Add the device to it once. Remove the device if it becomes unavailable (but I'm guessing that if the service is running then your device is available so you shouldn't need to do this). If you do need to remove the device, then you can re-add it when whatever condition caused you to remove it changes.

Once you have a single publisher (per NIC) running, with the device added, the system will respond to search requests from clients. Clients should explicitly search for your service if they have an immediate need to locate it, so there is no need to force constantly notifications. Each publisher will also send out periodic notifications of the device availability for you automatically, so any client that is listening for notifications will get them on an appropriate interval based on the SSDP spec.

Repeatedly publishing the device like you are;

1. Is incorrect use the library, and so massively inefficient. It's allocating and de-allocating many objects unneccesarily, sending many network packages and so on.

2. Goes against the SSDP specification. The SSPD spec contains specific logic for when broadcast notifications should be sent, to avoid flooding the network with multicast packets and causing network congestion. By republishing every few seconds you defeating the logic and risk creating issues for not only yourself, but other network devices.

**Comment by Reginiano** [comment]
Thank you Yorkw for your detailed response (as usual)!

Now i get it!
The thing is that the heartbeat is not so often, so when scanning for upnp devices (with device spy for example)- we sometimes need to wait for 15 minutes in order to capture the broadcast.
But i read what you wrote in another issue and i guess nothing "standard" can be done. Right?

**Comment by Yortw** [comment]
It's been a while since I used Device Spy and I don't currently have it installed to check, but I think there is a menu option to perform an explicit search.

Any client that wants to know right now what devices are available should perform a search. The notifications are useful for detecting when services go away (byebye notification), or if you've previously done a search while a device was off/disconnected and it then starts/restarts - you don't have to search again. They're not designed to be the primary mechansim for locating deviecs though, they're an added benefit on top of the explicit search (not a replacement for).
