### ISSUE TITLE
Question: How to publish services?

### ISSUE THREAD

**Issue by LukePulverenti** [Yortw/RSSDP#39]
Consider this example

NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=1800
LOCATION: http://10.0.0.1:64321/DmsDesc.xml
NT: urn:schemas-upnp-org:service:ConnectionManager:1
NTS: ssdp:alive
SERVER: Linux/2.6 UPnP/1.0 NEX-6/1.0
USN: uuid:00000000-0000-0010-8000-2002af0fa742::urn:schemas-upnp-org:service:ConnectionManager:1

FullDeviceType has the text device hard-coded:

https://github.com/Yortw/RSSDP/blob/46d16ed4dbca990a49a7b0f5260f9d25e79c2393/src/Main/RSSDP.Portable/SsdpDevice.cs#L162

In my fork I added a DeviceClass string property which defaults to device but can be customized to service.

Am I correct that without this there is no way for RSSDP to broadcast an alive message for this? The publishing example does not included embedded devices so I wasn't sure. If this is not currently supported then I can submit a pull request. Thanks.

**Comment by Yortw** [comment]
> Am I correct that without this there is no way for RSSDP to broadcast an alive message for this?

Yes, correct at this time.

> The publishing example does not included embedded devices so I wasn't sure. 

Nested *devices* should work, but services are not supported. This was intentional at the time as I only needed device support and services seemed like significant effort and something that could be added later.

I believe my plan was;

- Create an SsdpService class (and any related types) for the service structure
- Add a Services collection (of SsdpService) to the SsdpDevice class (I recall servers are 'owned' by devices?)
- Alter the device description document generation to handle the services
- Alter the publisher to respond to search requests & send notifications for services.

I think I assumed, given the search responses & notifications point to the location of the 'Device Description Document' which is the entire tree for that device, that the locator would still return the associated SsdpDevice when a service search was performed. Please let me know if that's not correct, as then I might need to spend a lot more time thinking about it.

I'm not sure when I'd have time to implement this, and I'm not too familiar with the services part of the spec. A pull request for this would be greatly appreciated, but only if you feel comfortable with doing that. Otherwise we can leave this open as a job to get it done when time allows.

**Comment by LukePulverenti** [comment]
Ok, thanks for the info. Since you were thinking about something larger and my change is only a workaround, it is probably best that I not submit it.

**Comment by Yortw** [comment]
Not intending to publish right away, but the main trunk should now include support for publishing services.
SsdpDevice objects have a Services property and AddService/RemoveService methods. There is a new SsdpService class used to describe the service data for publishing.

At the moment the SsdpService class contains only the data required for publishing the service and creating the Device Description Document service values, it does *not* contain sufficient detail to create a service description document. However it could be extended to do this if required.
