### ISSUE TITLE
Alive Notification Broadcast Interval

### ISSUE THREAD

**Issue by Yortw** [Yortw/RSSDP#41]
Some client applications would like to control how often alive notifications are sent, rather than relying on the randomised interval suggested by the SSDP specification.

Suggested solution: Add a 'NotificationBroadcastInterval' property of type TimeSpan to the SsdpDevicePublisher with a default value of TimeSpan.Zero. A value of TimeSpan.Zero will default to the existing randomised behaviour. Any other value will be used as a repeating interval from start of the publisher.

Questions: 

- The SSDP specification specifies a minimum broadcast interval (15 minutes?) - should values less than this be ignored/generate an error?

- With the property being present on the publisher rather than individual devices seems easy to manage and probably all that is required, however moving the property to the device class would allow different intervals for different devices. This would also increase the complexity of the broadcast scheduling logic slightly.

**Comment by Yortw** [comment]
@LukePulverenti Would appreciate your input on this, since it's a feature you raised as being important to you. Thanks.

**Comment by Yortw** [comment]
While implementing this change we should also look at this reported issue in the same code;

> 
> One thing about the current approach is that the timer has to be changed everytime it fires. This is OK but if you configure the cache length in a way that causes this condition to be hit:
> https://github.com/Yortw/RSSDP/blob/master/src/Main/RSSDP.Portable/SsdpDevicePublisherBase.cs#L559
> Then it will return and stop sending messages indefinitely until a device is added or removed. If I can recall how I created that situation I will let you know. In the end, I found it simpler just to have a timer fire at an interval so that it doesn't have to be continuously updated.

**Comment by LukePulverenti** [comment]
Yes an option for this would be great. For the default behavior, whichever you prefer is fine, it won't matter if it's configurable. 

I would not raise errors relating to interval duration, instead just let the consumer configure how they wish. I personally do not know what the ideal default interval is. The spec might say 15 minutes, but pretty much every upnp app that exposes this as a setting usually defaults to something like 30-60 seconds. What also poses a problem is that we've seen some devices that only listen for notify broadcasts and never send out any search requests. This is the type of situation where you need the very short interval.

Having the library default to spec is fine though, and if you're in a controlled environment with a predicable set of devices you might not need anything else.

As far as per device timer, I don't think it's necessary. Not only does create additional testing but it also means you need to have a timer per device instead of a single global one.

**Comment by Yortw** [comment]
@LukePulverenti It would be great if you could recall the situation that caused the rebroadcast timer to stop. Looking at the code, the timer is set to fire on a repeating interval. The condition you linked to that causes it to return early is there to stop the timer being recreated unnecessarily - the return occurs before the timer is disposed (so it is still active) and should have previously been configured with a repeating interval, so I can't see why this would cause it to stop. I will keep investigating, but if you can recall/explain the situation you encountered that would be great. Thanks.

**Comment by Yortw** [comment]
Wait, I think I see the problem now. Thanks.
