### ISSUE TITLE
Is it possible to specify a non-standard port number to this library?

### ISSUE THREAD

**Issue by huming2207** [Yortw/RSSDP#48]
Hello,

I've just bought a Xiaomi YeeLight wifi lightbulb. It offers an open API for geeks who knows how to programming on it. But I've checked their API document spec, it mentioned that they are using SSDP protocol with a non-standard port number, which is 1982 instead of standard port 1900. (See here: [Yeelight spec (English)](http://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf))

So I would like to ask that, is it possible that I can use this library directly and specify the port number, instead of editing source code?

Thanks in advance!
Jackson

**Comment by Yortw** [comment]
Hi, 

Sorry, but this is not possible with the current library (without modifying the source). You can specify a different *local* port, to avoid conflicts, but not the multicast port. Since the SSDP addresses and port are officially assigned by IANA and part of the protocol itself (http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=upnp https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol), and since devices broadcasting/listening on a different port won't find each other, I didn't see any use for being able to change them. While there's nothing stopping the rest of the protocol from running on other addresses/ports, the whole point of service discovery protocols is to eliminate the user having to configure network stuff they don't understand, hence the use of standard addresses and ports to ensure everything just works. If everybody chose different ports, we'd be back to manual config.

I honestly don't know what Xiaomi were thinking using a different port. There doesn't seem to be any good reason for it.

Your options are;

1. Fork the source and modify it. Should be pretty easy, the SsdpConstants class has a MulticastPort constant. Change that to have the value 1982 and that should be it.

2. You could do a proper job of making the port customisable and submit it back as a PR. Good PR's are always appreciated. However this would be more work, as it would need to maintain backwards compatibility for existing users, follow existing patterns in the code, and have appropriate /// comments and unit tests. It might also be worth a conversation first, as it may be time to stop adding more and more overloads of the constructor to the comms server and instead add just one more that takes an arguments class which we can extend in the future. If the PR is good and saves me having to write the code, then I can make the time to do the merge and release.

3. Wait for me to decide it's important, but to be honest my time for OSS is limited and I have higher priorities for both this library and others. I wouldn't count on me getting this done anytime soon, sorry.

If you want to fork and release as a separate library then the license supports that and I have no issue, but I would ask that you fully rename the dlls/assemblies/namespaces/packages etc. so that projects could reference both libraries without conflicts.

**Comment by huming2207** [comment]
Hello @Yortw ,

I'll try modify this library and create a pull request later if I'm free then. Currently I'm working on writing a new library for Yeelight as it seems doesn't also have a standard response after SSDP multicast request has been sent.

Here is a flow chart screenshot taken from their API manual:

<img width="700" alt="wx20170212-151056 2x" src="https://cloud.githubusercontent.com/assets/4463497/22860339/9428e42c-f135-11e6-95b9-c292c9f06378.png">


Here is an example of the response:
```
HTTP/1.1 200 OK
Cache-Control: max-age=3600
Date:
Ext:
Location: yeelight://192.168.1.239:55443
Server: POSIX UPnP/1.0 YGLC/1
id: 0x000000000015243f
model: color
fw_ver: 18
support: get_prop set_default set_power toggle set_bright start_cf stop_cf set_scene
cron_add cron_get cron_del set_ct_abx set_rgb
power: on
bright: 100
color_mode: 2
ct: 4000
rgb: 16711680
hue: 100
sat: 35
name: my_bulb
```

They return a non-standard schema over UDP instead of giving an information over HTTP with a XML schema.

By the way, for the reason why Xiaomi Yeelight doesn't run SSDP on a standard port, they said in their manual as they hope  "avoiding excessive multi-cast messages being received by
both smart LED and 3rd party devices. ". It's common that some of the Chinese IoT factories like doing those working but strange solutions.

As a result, I guess I should write another specific library for Xiaomi Yeelight by myself. It's more efficient with better compatibility.

Regards,
Jackson Hu.

**Comment by Yortw** [comment]
Hi,

If it's not really SSDP then that explains the custom port. The data you've shown looks mostly compatible, except *possibly* for the empty date header, and defintely for the custom protocol on the location url.

Feel free to fork this library and customize it for yeelight if you like. Some of the code, such as the http parser might well be useful. Entirely up to you.

Thanks.
