### ISSUE TITLE
How create Location file and share

### ISSUE THREAD

**Issue by fryette** [Yortw/RSSDP#58]
How create location file and share it on the UWP(Windows 10)
I don't know how right share file throw network.
Unfortunately I cannot find it in the description

**Comment by fryette** [comment]
The answer is run your own web server in app
e.x. with using this library https://github.com/sensaura-public/iotweb

**Comment by Yortw** [comment]
Hi,

I'm sorry, I appreciate there seems to be a language barrier here, but I'm not sure what you're asking in your original question. You seem to have found an answer anyway, which is good, but just for further clarification;

RSSDP can generate the xml (device description document) that represents the details of an SSDP device. Create an SsdpRootDevice instance and set properties on it to control the content of the XML. You can also add embedded devices/services to thsi instance. There is a validator class you can pass the device instance to in order to ensure the properties are set correctly/all required properties have values. When done you can call the ToDescriptionDocument to obtain the xml.

RSSDP is not, and does not contain, a web server. In order to provide the HTTP end point that servers the XML you'll need to either use a framework & server such as WCF, WebAPI with IIS/Cassini/NancyFx etc, write your own server using HttpListener if your platform supports it, or use one of the many existing http server projects such as https://github.com/sensaura-public/iotweb which you have already found.

Good luck!

**Comment by fryette** [comment]
Thank you @Yortw  for you answer. 
Sorry for language. 
Also I noticed, that when I run search(I copy and test code in examples on the UWP) I had a lot of exceptions like connection was failed, or host have been disconnected

**Comment by Yortw** [comment]
No problem about the language, just trying to make sure we understand each other.

Are you getting that error on the line 

```c#
var fullDevice = await foundDevice.GetDeviceInfo();
```
? Someone else had a similar sounding issue, and the problem was that one/some of their devices were reporting an incorrect address (or were restarting etc. and therefore not available). The GetDeviceInfo call should be in an try/catch in production code, because networking issues do happen.

**Comment by fryette** [comment]
@Yortw 
I retested application
I commented this line, but I still receive this exception
Also I tied to be in try/catch, and it doesn't help me, I still receive unhandled exception.
It not a big issue, I can live with it, but when you debug code, sometimes it difficult, because you have 10 or more exception one by one.

**Comment by Yortw** [comment]
Maybe you have break on all exceptions turned on in the VS? Trying turning that off, or using the 'rese't button on the toolbar of the Exceptions tool window.

**Comment by fryette** [comment]
@Yortw Oh, sure!
I'll check it soon and will answer you
Right now I don't have my laptop at hand

**Comment by fryette** [comment]
Unfortunately it didn't work for me.
I was disable all exceptions breaks, and still receive exception
