### ISSUE TITLE
Heartbeat

### ISSUE THREAD

**Issue by smartmeter** [Yortw/RSSDP#7]
Hello, how can I piggy back a heart beat in this. 

What should I do to configure the packets, so that I dont get my messages to get tagged into Dos packet.

**Comment by Yortw** [comment]
Hi

I'm not sure entirely what you're asking.

If by 'heartbeat' you mean a periodic notification (via the SSDP protocol) that a service is still alive, then this is built into both the SSDP specification and the RSSDP implementation. For the first service registered, and then after each 'heartbeat' is sent, the system determines the next heartbeat interval and sets an internal timer. When that timer fires, SSDP 'alive' notifications for each currently registered service are sent. The interval is determined as per the SSDP spec, which from memory (and paraphrasing) is 'a random time between 15 minutes and 1/2 the alive time of the service'. 15 minutes is the minimum, and I believe the reasoning for that is to help prevent flooding the network with unicast messages. The randomisation also helps prevent flooding the network when all SSDP broadcasters start at once. In RSSDP we take the greater of 15 minutes or a random time up to half the *minimum* alive/cache time of any service registered in the publisher

There isn't currently a way to force a manual notification to be sent. You could unregister and re-register the service with the publisher, but that would have the unwanted side affect of sending a 'bye bye' notification on unregister which is probably undesirable. It would be possible to add a method to force an alive notification to be sent, but I am not keen to do so as the spec already covers providing a heart beat designed not to flood the network and I suspect a manual option would be abused. 

The RSSDP design is to follow the spec, and make this sort of thing automatic. Between the existing heartbeat, alive notifications on register & publisher start and the bye bye notifications on a clean shutdown/unregister then I think you're pretty well covered. Even a heartbeat that occurs more often than the SSDP spec suggests wouldn't protect you from having to write clients that gracefully detect a service disappearing or being unavailable unexpectedly when called. It *might* reduce how often it happens, particularly with services that pop up and down often or on flaky networks, but in that case the heartbeats might well get missed or cause race conditions anyway, and so you still need a robust client for the unexpected.

If you're asking for some other (higher/lower level heartbeat), then that is beyond the scope of this library.

As for the DOS issue, I'm afraid I don't know. I'm not an expert at networking. I've implemented the SSDP spec over UDP (as the spec suggests/expects) using the high level .Net classes for UDP. As far as I know the only things I can 'configure' on a packet is the destination (address and port) and the content, there is no packet header or metadata that I'm aware of. I would expect that if you're configuring a firewall or QoS system to prevent DOS issues then you would configure that system to inspect the packets and apply rules, not configure the packets to it's requirements (but then as I said, I don't really know networking). That seems particularly true since you might have multiple systems sending the same type of packets and not all systems might support configuring the packets themselves.

My guess is the DOS system should allow UDP packets to the multicast address & port used by the SSDP spec, where the package contains a valid HTTP header (request or response on the first line). Perhaps it would include some sort of rate limiting based on source address, but that seems dangerous since you don't know how many services any given source might have and each SSDP message is supposed to be sent at least 3 times to account for possible packet loss over UDP. Perhaps it could detect a block packages are a certain number of exact duplicates are sent in a particular time span, but the limit would have to be more than 3 over several seconds (10?) to ensure it didn't block good packets.

If you know more about this than I do, and can explain to me what I need to do to modify the packets so they are accepted by general DOS protection systems then I'm happy to look into it. Likewise, if I've misunderstood one of your queries, please clarify and I'll attempt to help.

Thanks.

**Comment by Yortw** [comment]
Apologies if my previous, long winded answer, sounded harsh. I was trying to be helpful and detailed.

Re the heartbeat issue, I should point out that if you have just a few clients you could also have them 'poll' for available by performanc a search. Then you would have control over how often that happened. I wouldn't do that with many clients though, as it may create unnccesary load on the network. Also seraching for a specific service by id, or perhaps a group of services by type would be better than searching for all services everytime unless you really need to do that.

**Comment by smartmeter** [comment]
Thanks :+1:
