### ISSUE TITLE
Not working with Xamarin.Android

### ISSUE THREAD

**Issue by kakone** [Yortw/RSSDP#76]
Hello,

I noticed with latest versions of Xamarin.Android that the devices search doesn't work anymore. Did you have the problem too ? The Socket.SendTo method seems to hang.

**Comment by Yortw** [comment]
Hi,

I'm afraid I only regularly use the UWP and desktop framework versions. The Android version did work last time I tried it, but that was a while ago and I haven't tried since. As far as I know nothing has changed in the lib that should have broken it - you are the first to report a problem with Android/Xamarin. Of course that doesn't mean it works.

I will try to look at it when I can, but my living and work situations are awkward right now and I actually don't know when that will be sorry. Would appreciate help if you're able to look at it, otherwise I will look when I can.

Do you have a specific version of Android.Xamarin you're testing on?

Do you know if it works if you go back to an older Android.Xamarin?

**Comment by Yortw** [comment]
Hi,

Not sure what the problem you're experiencing is. Are you still having it?
I just created a brand new Xamarin Forms project, upgraded all the packages to the latest stable release and deployed some test code to a Samsung S8 - it finds 48 devices on my test network no problem.

Have you tried creating the locator with a specific IP address (the one for the wifi adapter), in case it's picking the cellular/vpn connection or something instead?

**Comment by Yortw** [comment]
BTW, I used the latest RSSDP package from Nuget for this test.

**Comment by kakone** [comment]
In fact, it works great. I did all my tests in an Android unit test project. There is a big problem in this kind of project because async methods don't work correctly. If I do the same tests in a classic Android app project, all works great.

**Comment by Yortw** [comment]
Sad to hear about that problem, but glad you found an answer/work around. Thanks for letting me know and closing the issue.
