### ISSUE TITLE
Rssdp Shared

### ISSUE THREAD

**Issue by risogolo** [Yortw/RSSDP#8]
I have included nuget package into my project (portable library), but I don't see classes from Shared folder, Am I doing something wrong?

**Comment by Yortw** [comment]
Hi,

I'm not sure. Which classes can you not see? Can you not see any classes? Can you see the RSSDP namespace?

You won't be able to see the SsdpDeviceLocator and SsdpDevicePublisher classes. These classes are platform specific (because the networking API's they use are platform specific and I didn't know about "bait and switch" ath the time I wrote this). 

If you're trying to use those in a PCL then your PCL classes need to use dependency injection... i.e the app will have to create those class instance and pass them to your PCL classes. Your PCL classes can expose a property or constructor argument of the base class type (from memory Rssdp.Infrastructure.DeviceLocatorBase/DevicePublisherBase). The base classes have all the same methods and properties as the implementation, so the PCL code can work with it fine, it just can't create it.

**Comment by risogolo** [comment]
Hi, I don't see these classes https://github.com/Yortw/RSSDP/tree/master/src/Main/Shared when I referenced RSSDP into PCL project (maybe because of dependencies). Now, I have referenced the library within UWP project and it is working fine, the thing is that I was planning to create a PCL library which was supposed to be referenced within ASP.NET 5 (Core CLR) WebAPI application, If there is not chance to make it work under PCL project, is it at least possible to make it work under ASP.NET 5 (Core CLR) WebAPI application? Not sure it this is possible, if it is, can you please try to add this option to the next release?

**Comment by Yortw** [comment]
So those classses are the ones that that are platform specific. You should be able to reference them from an app if it’s one of the support platforms, but not from the PCL. The PCL code has to deal with the base classes.

Unfortunately I don't have CoreFX support at the moment, and am not even sure if the CoreFX supports the API's I need (it might well, I just haven't looked).

I've used this a web API (hosted in a Windows app running full framework) but not Core CLR which no doubt requires some work. However I'm not sure about your use case in the first place... I don't believe SSDP works (or at least works well) over the internet. It's designed for finding devices on local networks. The internet seems to me to be too large an area to try and multicast packets over, plus it might return millions of devices, and many internet routers may not even support multicase on the internet facing side.

Do you know if SSDP is supposed to work on the public internet? I suspect you might need an alternate solution, one that uses some kind of service registration with a central authority rather than a broadcast search.

**Comment by risogolo** [comment]
I meant to integrate your RSSDP with WebAPI so then WebAPI application can communicate with the device and also expose REST methods on the internet, so the client can communicate with the device "over the internet"

**Comment by Yortw** [comment]
Right, gotcha.
Well, it should be possible with a full framework ASP .Net app, but at the moment no core fx support. I'll add it to the list of things to do, but TBH my focus is on other projects at the moment.

I'd be happy to look at a PR if you want to make an attempt yourself.

**Comment by risogolo** [comment]
maybe ;) thank you!

**Comment by Yortw** [comment]
Closed, as not currently support. See #9 for current status of required feature.
